smash error: fg: jobs list is empty
smash> smash error: fg: job-id 1 does not exist
smash> smash> smash> smash>  sleep 5   & : 5
smash> [1] sleep 1000& : 6 6 secs
[3] sleep 3000& : 7 4 secs
smash> smash error: fg: job-id 4 does not exist
smash> smash error: fg: invalid arguments
smash> [1] sleep 1000& : 6 7 secs
[3] sleep 3000& : 7 5 secs
smash> smash> smash> [1] sleep 1000& : 6 10 secs
[3] sleep 3000& : 7 8 secs
[4] sleep 90& : 8 2 secs
smash> smash error: fg: invalid arguments
smash> smash error: fg: invalid arguments
smash> smash error: fg: invalid arguments
smash> sleep 1000& : 6
smash: got ctrl-Z
smash: process 6 was stopped
smash> smash> [1] sleep 1000& : 6 2 secs (stopped)
[3] sleep 3000& : 7 15 secs
[4] sleep 90& : 8 9 secs
smash> sleep 3000& : 7
smash: got ctrl-C
smash: process 7 was killed
smash> [1] sleep 1000& : 6 5 secs (stopped)
[4] sleep 90& : 8 12 secs
smash> smash: got ctrl-Z
smash: got ctrl-C
sleep 1000& : 6
smash: got ctrl-C
smash: process 6 was killed
smash> smash error: fg: job-id 2 does not exist
smash> smash: got ctrl-C
smash error: fg: job-id 3 does not exist
smash> smash: got ctrl-C
sleep 90& : 8
smash: got ctrl-C
smash: process 8 was killed
smash> smash> 
